# Generated by Django 3.2.8 on 2021-10-07 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContentAudio',
            fields=[
                ('contentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contentbase')),
                ('bitrate', models.IntegerField()),
            ],
            bases=('core.contentbase',),
        ),
        migrations.CreateModel(
            name='ContentText',
            fields=[
                ('contentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contentbase')),
                ('text', models.TextField()),
            ],
            bases=('core.contentbase',),
        ),
        migrations.CreateModel(
            name='ContentVideo',
            fields=[
                ('contentbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.contentbase')),
                ('url_video', models.CharField(max_length=250)),
                ('url_subtitles', models.CharField(max_length=250)),
            ],
            bases=('core.contentbase',),
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_order', models.PositiveIntegerField(blank=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentbase')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.page')),
            ],
        ),
        migrations.AddField(
            model_name='contentbase',
            name='page',
            field=models.ManyToManyField(blank=True, through='core.PageContent', to='core.Page'),
        ),
    ]
