# Generated by Django 3.2.8 on 2021-10-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbase',
            name='page',
            field=models.ManyToManyField(blank=True, to='core.Page'),
        ),
    ]
