# Generated by Django 3.2.8 on 2021-10-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecontent',
            options={'ordering': ['-relative_order']},
        ),
        migrations.AlterField(
            model_name='pagecontent',
            name='relative_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
