# Generated by Django 3.2.8 on 2021-10-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_contentbase_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbase',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
